name: binary-search-tree

dependencies:
  - base

library:
  exposed-modules: BST
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - binary-search-tree
      - hspec
