name: beer-song

dependencies:
  - base

library:
  exposed-modules: Beer
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - beer-song
      - hspec
