name: forth

dependencies:
  - base
  - text

library:
  exposed-modules: Forth
  source-dirs: src
  dependencies:
    - containers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - forth
      - hspec
