~ "yacht.ua" ~ Score

# Yacht
⍤⤙≍ 50 Score [5 5 5 5 5] "yacht"

# Not Yacht
⍤⤙≍ 0 Score [1 3 3 2 5] "yacht"

# Ones
⍤⤙≍ 3 Score [1 1 1 3 5] "ones"

# Ones, out of order
⍤⤙≍ 3 Score [3 1 1 5 1] "ones"

# No ones
⍤⤙≍ 0 Score [4 3 6 5 5] "ones"

# Twos
⍤⤙≍ 2 Score [2 3 4 5 6] "twos"

# Fours
⍤⤙≍ 8 Score [1 4 1 4 1] "fours"

# Yacht counted as threes
⍤⤙≍ 15 Score [3 3 3 3 3] "threes"

# Yacht of 3s counted as fives
⍤⤙≍ 0 Score [3 3 3 3 3] "fives"

# Fives
⍤⤙≍ 10 Score [1 5 3 5 3] "fives"

# Sixes
⍤⤙≍ 6 Score [2 3 4 5 6] "sixes"

# Full house two small, three big
⍤⤙≍ 16 Score [2 2 4 4 4] "full house"

# Full house three small, two big
⍤⤙≍ 19 Score [5 3 3 5 3] "full house"

# Two pair is not a full house
⍤⤙≍ 0 Score [2 2 4 4 5] "full house"

# Four of a kind is not a full house
⍤⤙≍ 0 Score [1 4 4 4 4] "full house"

# Yacht is not a full house
⍤⤙≍ 0 Score [2 2 2 2 2] "full house"

# Four of a Kind
⍤⤙≍ 24 Score [6 6 4 6 6] "four of a kind"

# Yacht can be scored as Four of a Kind
⍤⤙≍ 12 Score [3 3 3 3 3] "four of a kind"

# Full house is not Four of a Kind
⍤⤙≍ 0 Score [3 3 3 5 5] "four of a kind"

# Little Straight
⍤⤙≍ 30 Score [3 5 4 1 2] "little straight"

# Little Straight as Big Straight
⍤⤙≍ 0 Score [1 2 3 4 5] "big straight"

# Four in order but not a little straight
⍤⤙≍ 0 Score [1 1 2 3 4] "little straight"

# No pairs but not a little straight
⍤⤙≍ 0 Score [1 2 3 4 6] "little straight"

# Minimum is 1, maximum is 5, but not a little straight
⍤⤙≍ 0 Score [1 1 3 4 5] "little straight"

# Big Straight
⍤⤙≍ 30 Score [4 6 2 5 3] "big straight"

# Big Straight as little straight
⍤⤙≍ 0 Score [6 5 4 3 2] "little straight"

# No pairs but not a big straight
⍤⤙≍ 0 Score [6 5 4 3 1] "big straight"

# Choice
⍤⤙≍ 23 Score [3 3 5 6 6] "choice"

# Yacht as choice
⍤⤙≍ 10 Score [2 2 2 2 2] "choice"
