name: zebra-puzzle

dependencies:
  - base

library:
  exposed-modules: ZebraPuzzle
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - zebra-puzzle
      - hspec
