name: connect

dependencies:
  - base

library:
  exposed-modules: Connect
  source-dirs: src
  dependencies:
    - array

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - connect
      - hspec
