name: robot-simulator

dependencies:
  - base

library:
  exposed-modules: Robot
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - robot-simulator
      - hspec
