~ "micro-blog.ua" ~ Truncate

# englishLanguageShort
⍤⤙≍ "Hi" Truncate "Hi"

# english language - long
⍤⤙≍ "Hello" Truncate "Hello there"

# german language - short - broth
⍤⤙≍ "brühe" Truncate "brühe"

# german language - long - bear carpet to beards
⍤⤙≍ "Bärte" Truncate "Bärteppich"

# bulgarian language - short - good
⍤⤙≍ "Добър" Truncate "Добър"

# greek language - short - health
⍤⤙≍ "υγειά" Truncate "υγειά"

# maths - short
⍤⤙≍ "a=πr²" Truncate "a=πr²"

# maths - kong
⍤⤙≍ "∅⊊ℕ⊊ℤ" Truncate "∅⊊ℕ⊊ℤ⊊ℚ⊊ℝ⊊ℂ"

# english - and emoji - short
⍤⤙≍ "Fly 🛫" Truncate "Fly 🛫"

# emoji - short
⍤⤙≍ "💇" Truncate "💇"

# emoji - long
⍤⤙≍ "❄🌡🤧🤒🏥" Truncate "❄🌡🤧🤒🏥🕰😀"

# royal flush
⍤⤙≍ "🃎🂸🃅🃋🃍" Truncate "🃎🂸🃅🃋🃍🃁🃊"
