name: triangle

dependencies:
  - base

library:
  exposed-modules: Triangle
  source-dirs: src
  dependencies:
    - containers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - triangle
      - hspec
