name: difference-of-squares

dependencies:
  - base

library:
  exposed-modules: Squares
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - difference-of-squares
      - hspec
