name: space-age

dependencies:
  - base

library:
  exposed-modules: SpaceAge
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - space-age
      - hspec
