name: phone-number

dependencies:
  - base

library:
  exposed-modules: Phone
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - phone-number
      - hspec
