name: pascals-triangle

dependencies:
  - base

library:
  exposed-modules: Triangle
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - pascals-triangle
      - hspec
