name: word-count

dependencies:
  - base

library:
  exposed-modules: WordCount
  source-dirs: src
  dependencies:
    - split

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - word-count
      - hspec
