~ "gigasecond.ua" ~ Gigasecond

# date only specification of time
⍤⤙≍ [2043 1 1 1 46 40] Gigasecond [2011 4 25 0 0 0]

# second test for date only specification of time
⍤⤙≍ [2009 2 19 1 46 40] Gigasecond [1977 6 13 0 0 0]

# third test for date only specification of time
⍤⤙≍ [1991 3 27 1 46 40] Gigasecond [1959 7 19 0 0 0]

# full time specified
⍤⤙≍ [2046 10 2 23 46 40] Gigasecond [2015 1 24 22 0 0]

# full time with day roll-over
⍤⤙≍ [2046 10 3 1 46 39] Gigasecond [2015 1 24 23 59 59]
