~ "resistor-color-duo.ua" ~ ResistorsValue

#Brown and black
⍤⤙≍ 10 ResistorsValue {"brown" "black"}

#Blue and grey
⍤⤙≍ 68 ResistorsValue {"blue" "grey"}

#Yellow and violet
⍤⤙≍ 47 ResistorsValue {"yellow" "violet"}

#White and red
⍤⤙≍ 92 ResistorsValue {"white" "red"}

#Orange and orange
⍤⤙≍ 33 ResistorsValue {"orange" "orange"}

#Ignore additional colors
⍤⤙≍ 51 ResistorsValue {"green" "brown" "orange"}

#Black and brown, one-digit
⍤⤙≍ 1  ResistorsValue {"black" "brown"}
