name: wordy

dependencies:
  - base

library:
  exposed-modules: WordProblem
  source-dirs: src
  dependencies:
    - text
    - attoparsec
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - wordy
      - hspec
