~ "line-up.ua" ~ Format

# format smallest non-exceptional ordinal numeral 4
⍤⤙≍ "Gianna, you are the 4th customer we serve today. Thank you!" Format "Gianna" 4

# format greatest single digit non-exceptional ordinal numeral 9
⍤⤙≍ "Maarten, you are the 9th customer we serve today. Thank you!" Format "Maarten" 9

# format non-exceptional ordinal numeral 5
⍤⤙≍ "Petronila, you are the 5th customer we serve today. Thank you!" Format "Petronila" 5

# format non-exceptional ordinal numeral 6
⍤⤙≍ "Attakullakulla, you are the 6th customer we serve today. Thank you!" Format "Attakullakulla" 6

# format non-exceptional ordinal numeral 7
⍤⤙≍ "Kate, you are the 7th customer we serve today. Thank you!" Format "Kate" 7

# format non-exceptional ordinal numeral 8
⍤⤙≍ "Maximiliano, you are the 8th customer we serve today. Thank you!" Format "Maximiliano" 8

# format exceptional ordinal numeral 1
⍤⤙≍ "Mary, you are the 1st customer we serve today. Thank you!" Format "Mary" 1

# format exceptional ordinal numeral 2
⍤⤙≍ "Haruto, you are the 2nd customer we serve today. Thank you!" Format "Haruto" 2

# format exceptional ordinal numeral 3
⍤⤙≍ "Henriette, you are the 3rd customer we serve today. Thank you!" Format "Henriette" 3

# format smallest two digit non-exceptional ordinal numeral 10
⍤⤙≍ "Alvarez, you are the 10th customer we serve today. Thank you!" Format "Alvarez" 10

# format non-exceptional ordinal numeral 11
⍤⤙≍ "Jacqueline, you are the 11th customer we serve today. Thank you!" Format "Jacqueline" 11

# format non-exceptional ordinal numeral 12
⍤⤙≍ "Juan, you are the 12th customer we serve today. Thank you!" Format "Juan" 12

# format non-exceptional ordinal numeral 13
⍤⤙≍ "Patricia, you are the 13th customer we serve today. Thank you!" Format "Patricia" 13

# format exceptional ordinal numeral 21
⍤⤙≍ "Washi, you are the 21st customer we serve today. Thank you!" Format "Washi" 21

# format exceptional ordinal numeral 22 ending in nd even though it is a multiple of 11
⍤⤙≍ "Ingrid, you are the 22nd customer we serve today. Thank you!" Format "Ingrid" 22

# format exceptional ordinal numeral 33 ending in rd even though it is a multiple of 11
⍤⤙≍ "Mario, you are the 33rd customer we serve today. Thank you!" Format "Mario" 33

# format exceptional ordinal numeral 52 ending in nd even though it is a multiple of 13
⍤⤙≍ "Quentin, you are the 52nd customer we serve today. Thank you!" Format "Quentin" 52

# format exceptional ordinal numeral 62
⍤⤙≍ "Nayra, you are the 62nd customer we serve today. Thank you!" Format "Nayra" 62

# format non-exceptional ordinal numeral 72 ending in nd even though it is a multiple of 12
⍤⤙≍ "Ugo, you are the 72nd customer we serve today. Thank you!" Format "Ugo" 72

# format exceptional ordinal numeral 91 ending in st even though it is a multiple of 13
⍤⤙≍ "Boris, you are the 91st customer we serve today. Thank you!" Format "Boris" 91

# format exceptional ordinal numeral 100
⍤⤙≍ "John, you are the 100th customer we serve today. Thank you!" Format "John" 100

# format exceptional ordinal numeral 101
⍤⤙≍ "Zeinab, you are the 101st customer we serve today. Thank you!" Format "Zeinab" 101

# format non-exceptional ordinal numeral 112
⍤⤙≍ "Knud, you are the 112th customer we serve today. Thank you!" Format "Knud" 112

# format exceptional ordinal numeral 123
⍤⤙≍ "Yma, you are the 123rd customer we serve today. Thank you!" Format "Yma" 123

# format large number 972 ending in nd even though it is a multiple of 12
⍤⤙≍ "Elias, you are the 972nd customer we serve today. Thank you!" Format "Elias" 972
