name: pov

dependencies:
  - base
  - containers

library:
  exposed-modules: POV
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - pov
      - hspec
