name: acronym
version: 1.4.0.6

dependencies:
  - base

library:
  exposed-modules: Acronym
  source-dirs: src
  dependencies:
    - split

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - acronym
      - hspec
