name: rotational-cipher

dependencies:
  - base

library:
  exposed-modules: RotationalCipher
  source-dirs: src
  dependencies:
    - text

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - rotational-cipher
      - hspec
