~ "killer-sudoku-helper.ua" ~ Combinations

# 1
⍤⤙≍ [[1]] Combinations [] 1 1

# 2
⍤⤙≍ [[2]] Combinations [] 1 2

# 3
⍤⤙≍ [[3]] Combinations [] 1 3

# 4
⍤⤙≍ [[4]] Combinations [] 1 4

# 5
⍤⤙≍ [[5]] Combinations [] 1 5

# 6
⍤⤙≍ [[6]] Combinations [] 1 6

# 7
⍤⤙≍ [[7]] Combinations [] 1 7

# 8
⍤⤙≍ [[8]] Combinations [] 1 8

# 9
⍤⤙≍ [[9]] Combinations [] 1 9

# Cage with sum 45 contains all digits 1:9
⍤⤙≍ [[1 2 3 4 5 6 7 8 9]] Combinations [] 9 45

# Cage with only 1 possible combination
⍤⤙≍ [[1 2 4]] Combinations [] 3 7

# Cage with several Combinations
⍤⤙≍ [[1 9] [2 8] [3 7] [4 6]] Combinations [] 2 10

# Cage with several Combinations that is restricted
⍤⤙≍ [[2 8] [3 7]] Combinations [1 4] 2 10
