~ "acronym.ua" ~ Acronym

# ignoring punctuation and casing?
⍤⤙≍ "CMOS" Acronym "Complementary metal-oxide semiconductor"

# ignores punctuation?
⍤⤙≍ "FIFO" Acronym "First In, First Out"

# from phrases with acronyms?
⍤⤙≍ "GIMP" Acronym "GNU Image Manipulation Program"

# from phrases with apostrophes?
⍤⤙≍ "HC" Acronym "Halley's Comet"

# from title case?
⍤⤙≍ "PNG" Acronym "Portable Network Graphics"

# from lower case?
⍤⤙≍ "ROR" Acronym "Ruby on Rails"

# from a very long abbreviation?
⍤⤙≍ "ROTFLSHTMDCOALM" Acronym "Rolling On The Floor Laughing So Hard That My Dogs Came Over And Licked Me"

# from phrases with consecutive delimiters?
⍤⤙≍ "SIMUFTA" Acronym "Something - I made up from thin air"

# from phrases with underscore emphasis?
⍤⤙≍ "TRNT" Acronym "The Road _Not_ Taken"
