~ "scrabble-score.ua" ~ Score

# lowercase letter?
⍤⤙≍ 1 Score "a"

# uppercase letter?
⍤⤙≍ 1 Score "A"

# valuable letter?
⍤⤙≍ 4 Score "f"

# short word?
⍤⤙≍ 2 Score "at"

# short, valuable word?
⍤⤙≍ 12 Score "zoo"

# medium word?
⍤⤙≍ 6 Score "street"

# medium, valuable word?
⍤⤙≍ 22 Score "quirky"

# long, mixed-case word?
⍤⤙≍ 41 Score "OxyphenButazone"

# english-like word?
⍤⤙≍ 8 Score "pinata"

# empty input?
⍤⤙≍ 0 Score ""

# entire alphabet available?
⍤⤙≍ 87 Score "abcdefghijklmnopqrstuvwxyz"
