name: sieve

dependencies:
  - base

library:
  exposed-modules: Sieve
  source-dirs: src
  dependencies:
    - vector

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - sieve
      - hspec
