name: hello-world

dependencies:
  - base

library:
  exposed-modules: HelloWorld
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - hello-world
      - hspec
