name: custom-set

dependencies:
  - base

library:
  exposed-modules: CustomSet
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - custom-set
      - hspec
