name: grade-school

dependencies:
  - base

library:
  exposed-modules: School
  source-dirs: src
  dependencies:
    - containers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - grade-school
      - hspec
