~ "roman-numerals.ua" ~ ToRoman

# 1 is I
⍤⤙≍ "I" ToRoman 1

# 2 is II
⍤⤙≍ "II" ToRoman 2

# 3 is III
⍤⤙≍ "III" ToRoman 3

# 4 is IV
⍤⤙≍ "IV" ToRoman 4

# 5 is V
⍤⤙≍ "V" ToRoman 5

# 6 is VI
⍤⤙≍ "VI" ToRoman 6

# 9 is IX
⍤⤙≍ "IX" ToRoman 9

# 27 is XXVII
⍤⤙≍ "XXVII" ToRoman 27

# 48 is XLVIII
⍤⤙≍ "XLVIII" ToRoman 48

# 49 is XLIX
⍤⤙≍ "XLIX" ToRoman 49

# 59 is LIX
⍤⤙≍ "LIX" ToRoman 59

# 93 is XCIII
⍤⤙≍ "XCIII" ToRoman 93

# 141 is CXLI
⍤⤙≍ "CXLI" ToRoman 141

# 163 is CLXIII
⍤⤙≍ "CLXIII" ToRoman 163

# 402 is CDII
⍤⤙≍ "CDII" ToRoman 402

# 575 is DLXXV
⍤⤙≍ "DLXXV" ToRoman 575

# 911 is CMXI
⍤⤙≍ "CMXI" ToRoman 911

# 1024 is MXXIV
⍤⤙≍ "MXXIV" ToRoman 1024

# 3000 is MMM
⍤⤙≍ "MMM" ToRoman 3000

# 16 is XVI
⍤⤙≍ "XVI" ToRoman 16

# 66 is LXVI
⍤⤙≍ "LXVI" ToRoman 66

# 166 is CLXVI
⍤⤙≍ "CLXVI" ToRoman 166

# 666 is DCLXVI
⍤⤙≍ "DCLXVI" ToRoman 666

# 1666 is MDCLXVI
⍤⤙≍ "MDCLXVI" ToRoman 1666

# 3001 is MMMI
⍤⤙≍ "MMMI" ToRoman 3001

# 3888 is MMMDCCCLXXXVIII
⍤⤙≍ "MMMDCCCLXXXVIII" ToRoman 3888

# 3999 is MMMCMXCIX
⍤⤙≍ "MMMCMXCIX" ToRoman 3999
