~ "prime-factors.ua" ~ Factors

# No factors
⍤⤙≍ [] Factors 1

# Prime number
⍤⤙≍ [2] Factors 2

# Another prime number
⍤⤙≍ [3] Factors 3

# Square of a prime
⍤⤙≍ [3 3] Factors 9

# Product of first prime
⍤⤙≍ [2 2] Factors 4

# Cube of a prime
⍤⤙≍ [2 2 2] Factors 8

# Product of second prime
⍤⤙≍ [3 3 3] Factors 27

# Product of third prime
⍤⤙≍ [5 5 5 5] Factors 625

# Product of first and second prime
⍤⤙≍ [2 3] Factors 6

# Product of primes and non-primes
⍤⤙≍ [2 2 3] Factors 12

# Product of primes
⍤⤙≍ [5 17 23 461] Factors 901255

# Factors include a large prime
⍤⤙≍ [11 9539 894119] Factors 93819012551
