name: rail-fence-cipher
version: 1.1.0.3

dependencies:
  - base

library:
  exposed-modules: RailFenceCipher
  source-dirs: src
  dependencies:
    - ilist

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - rail-fence-cipher
      - hspec
