name: atbash-cipher

dependencies:
  - base

library:
  exposed-modules: Atbash
  source-dirs: src
  dependencies:
    - text

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - atbash-cipher
      - hspec
