~ "high-scores.ua" ~ Latest PersonalBest PersonalTopThree Scores

# List of scores?
⍤⤙≍ [30 50 20 70] Scores [30 50 20 70]

# Latest score?
⍤⤙≍ 30 Latest [100 0 90 30]

# Personal best?
⍤⤙≍ 100 PersonalBest [40 100 70]

# Personal top three from a list of scores?
⍤⤙≍ [100 90 70] PersonalTopThree [10 30 90 30 100 20 10 0 30 40 40 70 70]

# Personal top highest to lowest?
⍤⤙≍ [30 20 10] PersonalTopThree [20 10 30]

# Personal top when there is a tie?
⍤⤙≍ [40 40 30] PersonalTopThree [40 20 40 30]

# Personal top when there are less than 3?
⍤⤙≍ [70 30] PersonalTopThree [30 70]

# Personal top when there is only one?
⍤⤙≍ [40] PersonalTopThree [40]
