~ "darts.ua" ~ Score

# Missed target?
⍤⤙≍ 0 Score ¯9 9

# On the outer circle?
⍤⤙≍ 1 Score 0 10

# On the middle circle?
⍤⤙≍ 5 Score ¯5 0

# On the inner circle?
⍤⤙≍ 10 Score 0 ¯1

# Exactly on center?
⍤⤙≍ 10 Score 0 0

# Near the center?
⍤⤙≍ 10 Score ¯0.1 ¯0.1

# Just within the inner circle?
⍤⤙≍ 10 Score 0.7 0.7

# Just outside the inner circle?
⍤⤙≍ 5 Score 0.8 ¯0.8

# Just within the middle circle?
⍤⤙≍ 5 Score ¯3.5 3.5

# Just outside the middle circle?
⍤⤙≍ 1 Score ¯3.6 ¯3.6

# Just within the outer circle?
⍤⤙≍ 1 Score ¯7 7

# Just outside the outer circle?
⍤⤙≍ 0 Score 7.1 ¯7.1

# Asymmetric position between the inner and middle circles?
⍤⤙≍ 5 Score 0.5 ¯4
