name: minesweeper

dependencies:
  - base

library:
  exposed-modules: Minesweeper
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - minesweeper
      - hspec
