~ "raindrops.ua" ~ Convert

# the sound of 1 is 1?
⍤⤙≍ "1" Convert 1

# the sound for 10 is Plang as it has a factor 5?
⍤⤙≍ "Plang" Convert 10

# the sound for 105 is PlingPlangPlong as it has factors 3 5 and 7?
⍤⤙≍ "PlingPlangPlong" Convert 105

# the sound for 14 is Plong as it has a factor of 7?
⍤⤙≍ "Plong" Convert 14

# the sound for 15 is PlingPlang as it has factors 3 and 5?
⍤⤙≍ "PlingPlang" Convert 15

# the sound for 21 is PlingPlong as it has factors 3 and 7?
⍤⤙≍ "PlingPlong" Convert 21

# the sound for 25 is Plang as it has a factor 5?
⍤⤙≍ "Plang" Convert 25

# the sound for 27 is Pling as it has a factor 3?
⍤⤙≍ "Pling" Convert 27

# the sound for 3 is Pling?
⍤⤙≍ "Pling" Convert 3

# the sound for 3125 is Plang as it has a factor 5?
⍤⤙≍ "Plang" Convert 3125

# the sound for 35 is PlangPlong as it has factors 5 and 7?
⍤⤙≍ "PlangPlong" Convert 35

# the sound for 49 is Plong as it has a factor 7?
⍤⤙≍ "Plong" Convert 49

# the sound for 5 is Plang?
⍤⤙≍ "Plang" Convert 5

# the sound for 52 is 52?
⍤⤙≍ "52" Convert 52

# the sound for 6 is Pling as it has a factor 3?
⍤⤙≍ "Pling" Convert 6

# the sound of 7 is Plong?
⍤⤙≍ "Plong" Convert 7

# 2 to the power 3 does not make a raindrop sound as 3 is the exponent not the base?
⍤⤙≍ "8" Convert 8

# the sound of 9 is Pling as it has a factor 3?
⍤⤙≍ "Pling" Convert 9
