name: sum-of-multiples

dependencies:
  - base

library:
  exposed-modules: SumOfMultiples
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - sum-of-multiples
      - hspec
