~ "pig-latin.ua" ~ Translate

# word beginning with a
⍤⤙≍ "appleay" Translate "apple"

# word beginning with e
⍤⤙≍ "earay" Translate "ear"

# word beginning with i
⍤⤙≍ "iglooay" Translate "igloo"

# word beginning with o
⍤⤙≍ "objectay" Translate "object"

# word beginning with u
⍤⤙≍ "underay" Translate "under"

# word beginning with a vowel and followed by a qu
⍤⤙≍ "equalay" Translate "equal"

# word beginning with p
⍤⤙≍ "igpay" Translate "pig"

# word beginning with k
⍤⤙≍ "oalakay" Translate "koala"

# word beginning with x
⍤⤙≍ "enonxay" Translate "xenon"

# word beginning with q without a following u
⍤⤙≍ "atqay" Translate "qat"

# word beginning with consonant and vowel containing qu
⍤⤙≍ "iquidlay" Translate "liquid"

# word beginning with ch
⍤⤙≍ "airchay" Translate "chair"

# word beginning with qu
⍤⤙≍ "eenquay" Translate "queen"

# word beginning with qu and a preceding consonant
⍤⤙≍ "aresquay" Translate "square"

# word beginning with th
⍤⤙≍ "erapythay" Translate "therapy"

# word beginning with thr
⍤⤙≍ "ushthray" Translate "thrush"

# word beginning with sch
⍤⤙≍ "oolschay" Translate "school"

# word beginning with yt
⍤⤙≍ "yttriaay" Translate "yttria"

# word beginning with xr
⍤⤙≍ "xrayay" Translate "xray"

# y is treated like a consonant at the beginning of a word
⍤⤙≍ "ellowyay" Translate "yellow"

# y is treated like a vowel at the end of a consonant cluster
⍤⤙≍ "ythmrhay" Translate "rhythm"

# y as second letter in two letter word
⍤⤙≍ "ymay" Translate "my"

# a whole phrase
⍤⤙≍ "ickquay astfay unray" Translate "quick fast run"
