// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var HelloWorld$HelloWorld = require("../src/HelloWorld.bs.js");

Jest.describe("Hello World", (function (param) {
        return Jest.test("says hello", (function (param) {
                      return Jest.Expect.toBe("Hello, World!", Jest.Expect.expect(HelloWorld$HelloWorld.hello(undefined)));
                    }));
      }));

/*  Not a pure module */
