name: alphametics

dependencies:
  - base

library:
  exposed-modules: Alphametics
  source-dirs: src
  dependencies:
    - parsec

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - alphametics
      - hspec
