name: dominoes

dependencies:
  - base

library:
  exposed-modules: Dominoes
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - dominoes
      - hspec
