~ "say.ua" ~ Say

# Zero
⍤⤙≍ "zero" Say 0

# One
⍤⤙≍ "one" Say 1

# Fourteen
⍤⤙≍ "fourteen" Say 14

# Twenty
⍤⤙≍ "twenty" Say 20

# Twenty-two
⍤⤙≍ "twenty-two" Say 22

# Thirty
⍤⤙≍ "thirty" Say 30

# Ninety-nine
⍤⤙≍ "ninety-nine" Say 99

# One hundred
⍤⤙≍ "one hundred" Say 100

# One hundred twenty-three
⍤⤙≍ "one hundred twenty-three" Say 123

# Two hundred
⍤⤙≍ "two hundred" Say 200

# Nine hundred ninety-nine
⍤⤙≍ "nine hundred ninety-nine" Say 999

# One thousand
⍤⤙≍ "one thousand" Say 1000

# One thousand two hundred thirty-four
⍤⤙≍ "one thousand two hundred thirty-four" Say 1234

# One million
⍤⤙≍ "one million" Say 1000000

# One million two thousand three hundred forty-five
⍤⤙≍ "one million two thousand three hundred forty-five" Say 1002345

# One billion
⍤⤙≍ "one billion" Say 1000000000

# A big number
⍤⤙≍ "nine hundred eighty-seven billion six hundred fifty-four million three hundred twenty-one thousand one hundred twenty-three" Say 987654321123

# Numbers below zero are out of range
⍤⤙≍ "input out of range" ⍣(Say ¯1)

# Numbers above 999,999,999,999 are out of range
⍤⤙≍ "input out of range" ⍣(Say 1000000000000)
