~ "meetup.ua" ~ Meetup

# when teenth Monday is the 13th, the first day of the teenth week
⍤⤙≍ [2013 5 13] Meetup 2013 5 "Monday" "teenth"

# when teenth Monday is the 19th, the last day of the teenth week
⍤⤙≍ [2013 8 19] Meetup 2013 8 "Monday" "teenth"

# when teenth Monday is some day in the middle of the teenth week
⍤⤙≍ [2013 9 16] Meetup 2013 9 "Monday" "teenth"

# when teenth Tuesday is the 19th, the last day of the teenth week
⍤⤙≍ [2013 3 19] Meetup 2013 3 "Tuesday" "teenth"

# when teenth Tuesday is some day in the middle of the teenth week
⍤⤙≍ [2013 4 16] Meetup 2013 4 "Tuesday" "teenth"

# when teenth Tuesday is the 13th, the first day of the teenth week
⍤⤙≍ [2013 8 13] Meetup 2013 8 "Tuesday" "teenth"

# when teenth Wednesday is some day in the middle of the teenth week
⍤⤙≍ [2013 1 16] Meetup 2013 1 "Wednesday" "teenth"

# when teenth Wednesday is the 13th, the first day of the teenth week
⍤⤙≍ [2013 2 13] Meetup 2013 2 "Wednesday" "teenth"

# when teenth Wednesday is the 19th, the last day of the teenth week
⍤⤙≍ [2013 6 19] Meetup 2013 6 "Wednesday" "teenth"

# when teenth Thursday is some day in the middle of the teenth week
⍤⤙≍ [2013 5 16] Meetup 2013 5 "Thursday" "teenth"

# when teenth Thursday is the 13th, the first day of the teenth week
⍤⤙≍ [2013 6 13] Meetup 2013 6 "Thursday" "teenth"

# when teenth Thursday is the 19th, the last day of the teenth week
⍤⤙≍ [2013 9 19] Meetup 2013 9 "Thursday" "teenth"

# when teenth Friday is the 19th, the last day of the teenth week
⍤⤙≍ [2013 4 19] Meetup 2013 4 "Friday" "teenth"

# when teenth Friday is some day in the middle of the teenth week
⍤⤙≍ [2013 8 16] Meetup 2013 8 "Friday" "teenth"

# when teenth Friday is the 13th, the first day of the teenth week
⍤⤙≍ [2013 9 13] Meetup 2013 9 "Friday" "teenth"

# when teenth Saturday is some day in the middle of the teenth week
⍤⤙≍ [2013 2 16] Meetup 2013 2 "Saturday" "teenth"

# when teenth Saturday is the 13th, the first day of the teenth week
⍤⤙≍ [2013 4 13] Meetup 2013 4 "Saturday" "teenth"

# when teenth Saturday is the 19th, the last day of the teenth week
⍤⤙≍ [2013 10 19] Meetup 2013 10 "Saturday" "teenth"

# when teenth Sunday is the 19th, the last day of the teenth week
⍤⤙≍ [2013 5 19] Meetup 2013 5 "Sunday" "teenth"

# when teenth Sunday is some day in the middle of the teenth week
⍤⤙≍ [2013 6 16] Meetup 2013 6 "Sunday" "teenth"

# when teenth Sunday is the 13th, the first day of the teenth week
⍤⤙≍ [2013 10 13] Meetup 2013 10 "Sunday" "teenth"

# when first Monday is some day in the middle of the first week
⍤⤙≍ [2013 3 4] Meetup 2013 3 "Monday" "first"

# when first Monday is the 1st, the first day of the first week
⍤⤙≍ [2013 4 1] Meetup 2013 4 "Monday" "first"

# when first Tuesday is the 7th, the last day of the first week
⍤⤙≍ [2013 5 7] Meetup 2013 5 "Tuesday" "first"

# when first Tuesday is some day in the middle of the first week
⍤⤙≍ [2013 6 4] Meetup 2013 6 "Tuesday" "first"

# when first Wednesday is some day in the middle of the first week
⍤⤙≍ [2013 7 3] Meetup 2013 7 "Wednesday" "first"

# when first Wednesday is the 7th, the last day of the first week
⍤⤙≍ [2013 8 7] Meetup 2013 8 "Wednesday" "first"

# when first Thursday is some day in the middle of the first week
⍤⤙≍ [2013 9 5] Meetup 2013 9 "Thursday" "first"

# when first Thursday is another day in the middle of the first week
⍤⤙≍ [2013 10 3] Meetup 2013 10 "Thursday" "first"

# when first Friday is the 1st, the first day of the first week
⍤⤙≍ [2013 11 1] Meetup 2013 11 "Friday" "first"

# when first Friday is some day in the middle of the first week
⍤⤙≍ [2013 12 6] Meetup 2013 12 "Friday" "first"

# when first Saturday is some day in the middle of the first week
⍤⤙≍ [2013 1 5] Meetup 2013 1 "Saturday" "first"

# when first Saturday is another day in the middle of the first week
⍤⤙≍ [2013 2 2] Meetup 2013 2 "Saturday" "first"

# when first Sunday is some day in the middle of the first week
⍤⤙≍ [2013 3 3] Meetup 2013 3 "Sunday" "first"

# when first Sunday is the 7th, the last day of the first week
⍤⤙≍ [2013 4 7] Meetup 2013 4 "Sunday" "first"

# when second Monday is some day in the middle of the second week
⍤⤙≍ [2013 3 11] Meetup 2013 3 "Monday" "second"

# when second Monday is the 8th, the first day of the second week
⍤⤙≍ [2013 4 8] Meetup 2013 4 "Monday" "second"

# when second Tuesday is the 14th, the last day of the second week
⍤⤙≍ [2013 5 14] Meetup 2013 5 "Tuesday" "second"

# when second Tuesday is some day in the middle of the second week
⍤⤙≍ [2013 6 11] Meetup 2013 6 "Tuesday" "second"

# when second Wednesday is some day in the middle of the second week
⍤⤙≍ [2013 7 10] Meetup 2013 7 "Wednesday" "second"

# when second Wednesday is the 14th, the last day of the second week
⍤⤙≍ [2013 8 14] Meetup 2013 8 "Wednesday" "second"

# when second Thursday is some day in the middle of the second week
⍤⤙≍ [2013 9 12] Meetup 2013 9 "Thursday" "second"

# when second Thursday is another day in the middle of the second week
⍤⤙≍ [2013 10 10] Meetup 2013 10 "Thursday" "second"

# when second Friday is the 8th, the first day of the second week
⍤⤙≍ [2013 11 8] Meetup 2013 11 "Friday" "second"

# when second Friday is some day in the middle of the second week
⍤⤙≍ [2013 12 13] Meetup 2013 12 "Friday" "second"

# when second Saturday is some day in the middle of the second week
⍤⤙≍ [2013 1 12] Meetup 2013 1 "Saturday" "second"

# when second Saturday is another day in the middle of the second week
⍤⤙≍ [2013 2 9] Meetup 2013 2 "Saturday" "second"

# when second Sunday is some day in the middle of the second week
⍤⤙≍ [2013 3 10] Meetup 2013 3 "Sunday" "second"

# when second Sunday is the 14th, the last day of the second week
⍤⤙≍ [2013 4 14] Meetup 2013 4 "Sunday" "second"

# when third Monday is some day in the middle of the third week
⍤⤙≍ [2013 3 18] Meetup 2013 3 "Monday" "third"

# when third Monday is the 15th, the first day of the third week
⍤⤙≍ [2013 4 15] Meetup 2013 4 "Monday" "third"

# when third Tuesday is the 21st, the last day of the third week
⍤⤙≍ [2013 5 21] Meetup 2013 5 "Tuesday" "third"

# when third Tuesday is some day in the middle of the third week
⍤⤙≍ [2013 6 18] Meetup 2013 6 "Tuesday" "third"

# when third Wednesday is some day in the middle of the third week
⍤⤙≍ [2013 7 17] Meetup 2013 7 "Wednesday" "third"

# when third Wednesday is the 21st, the last day of the third week
⍤⤙≍ [2013 8 21] Meetup 2013 8 "Wednesday" "third"

# when third Thursday is some day in the middle of the third week
⍤⤙≍ [2013 9 19] Meetup 2013 9 "Thursday" "third"

# when third Thursday is another day in the middle of the third week
⍤⤙≍ [2013 10 17] Meetup 2013 10 "Thursday" "third"

# when third Friday is the 15th, the first day of the third week
⍤⤙≍ [2013 11 15] Meetup 2013 11 "Friday" "third"

# when third Friday is some day in the middle of the third week
⍤⤙≍ [2013 12 20] Meetup 2013 12 "Friday" "third"

# when third Saturday is some day in the middle of the third week
⍤⤙≍ [2013 1 19] Meetup 2013 1 "Saturday" "third"

# when third Saturday is another day in the middle of the third week
⍤⤙≍ [2013 2 16] Meetup 2013 2 "Saturday" "third"

# when third Sunday is some day in the middle of the third week
⍤⤙≍ [2013 3 17] Meetup 2013 3 "Sunday" "third"

# when third Sunday is the 21st, the last day of the third week
⍤⤙≍ [2013 4 21] Meetup 2013 4 "Sunday" "third"

# when fourth Monday is some day in the middle of the fourth week
⍤⤙≍ [2013 3 25] Meetup 2013 3 "Monday" "fourth"

# when fourth Monday is the 22nd, the first day of the fourth week
⍤⤙≍ [2013 4 22] Meetup 2013 4 "Monday" "fourth"

# when fourth Tuesday is the 28th, the last day of the fourth week
⍤⤙≍ [2013 5 28] Meetup 2013 5 "Tuesday" "fourth"

# when fourth Tuesday is some day in the middle of the fourth week
⍤⤙≍ [2013 6 25] Meetup 2013 6 "Tuesday" "fourth"

# when fourth Wednesday is some day in the middle of the fourth week
⍤⤙≍ [2013 7 24] Meetup 2013 7 "Wednesday" "fourth"

# when fourth Wednesday is the 28th, the last day of the fourth week
⍤⤙≍ [2013 8 28] Meetup 2013 8 "Wednesday" "fourth"

# when fourth Thursday is some day in the middle of the fourth week
⍤⤙≍ [2013 9 26] Meetup 2013 9 "Thursday" "fourth"

# when fourth Thursday is another day in the middle of the fourth week
⍤⤙≍ [2013 10 24] Meetup 2013 10 "Thursday" "fourth"

# when fourth Friday is the 22nd, the first day of the fourth week
⍤⤙≍ [2013 11 22] Meetup 2013 11 "Friday" "fourth"

# when fourth Friday is some day in the middle of the fourth week
⍤⤙≍ [2013 12 27] Meetup 2013 12 "Friday" "fourth"

# when fourth Saturday is some day in the middle of the fourth week
⍤⤙≍ [2013 1 26] Meetup 2013 1 "Saturday" "fourth"

# when fourth Saturday is another day in the middle of the fourth week
⍤⤙≍ [2013 2 23] Meetup 2013 2 "Saturday" "fourth"

# when fourth Sunday is some day in the middle of the fourth week
⍤⤙≍ [2013 3 24] Meetup 2013 3 "Sunday" "fourth"

# when fourth Sunday is the 28th, the last day of the fourth week
⍤⤙≍ [2013 4 28] Meetup 2013 4 "Sunday" "fourth"

# last Monday in a month with four Mondays
⍤⤙≍ [2013 3 25] Meetup 2013 3 "Monday" "last"

# last Monday in a month with five Mondays
⍤⤙≍ [2013 4 29] Meetup 2013 4 "Monday" "last"

# last Tuesday in a month with four Tuesdays
⍤⤙≍ [2013 5 28] Meetup 2013 5 "Tuesday" "last"

# last Tuesday in another month with four Tuesdays
⍤⤙≍ [2013 6 25] Meetup 2013 6 "Tuesday" "last"

# last Wednesday in a month with five Wednesdays
⍤⤙≍ [2013 7 31] Meetup 2013 7 "Wednesday" "last"

# last Wednesday in a month with four Wednesdays
⍤⤙≍ [2013 8 28] Meetup 2013 8 "Wednesday" "last"

# last Thursday in a month with four Thursdays
⍤⤙≍ [2013 9 26] Meetup 2013 9 "Thursday" "last"

# last Thursday in a month with five Thursdays
⍤⤙≍ [2013 10 31] Meetup 2013 10 "Thursday" "last"

# last Friday in a month with five Fridays
⍤⤙≍ [2013 11 29] Meetup 2013 11 "Friday" "last"

# last Friday in a month with four Fridays
⍤⤙≍ [2013 12 27] Meetup 2013 12 "Friday" "last"

# last Saturday in a month with four Saturdays
⍤⤙≍ [2013 1 26] Meetup 2013 1 "Saturday" "last"

# last Saturday in another month with four Saturdays
⍤⤙≍ [2013 2 23] Meetup 2013 2 "Saturday" "last"

# last Sunday in a month with five Sundays
⍤⤙≍ [2013 3 31] Meetup 2013 3 "Sunday" "last"

# last Sunday in a month with four Sundays
⍤⤙≍ [2013 4 28] Meetup 2013 4 "Sunday" "last"

# when last Wednesday in February in a leap year is the 29th
⍤⤙≍ [2012 2 29] Meetup 2012 2 "Wednesday" "last"

# last Wednesday in December that is also the last day of the year
⍤⤙≍ [2014 12 31] Meetup 2014 12 "Wednesday" "last"

# when last Sunday in February in a non-leap year is not the 29th
⍤⤙≍ [2015 2 22] Meetup 2015 2 "Sunday" "last"

# when first Friday is the 7th, the last day of the first week
⍤⤙≍ [2012 12 7] Meetup 2012 12 "Friday" "first"
