name: food-chain

dependencies:
  - base

library:
  exposed-modules: FoodChain
  source-dirs: src
  dependencies:
    - array

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - food-chain
      - hspec
