name: secret-handshake

dependencies:
  - base

library:
  exposed-modules: SecretHandshake
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - secret-handshake
      - hspec
