~ "difference-of-squares.ua" ~ DifferenceOfSquares SquareOfSum SumOfSquares

# square of sum 1?
⍤⤙≍ 1 SquareOfSum 1

# square of sum 5?
⍤⤙≍ 225 SquareOfSum 5

# square of sum 100?
⍤⤙≍ 25502500 SquareOfSum 100

# sum of squares 1?
⍤⤙≍ 1 SumOfSquares 1

# sum of squares 5?
⍤⤙≍ 55 SumOfSquares 5

# sum of squares 100?
⍤⤙≍ 338350 SumOfSquares 100

# difference of squares 1?
⍤⤙≍ 0 DifferenceOfSquares 1

# difference of squares 5?
⍤⤙≍ 170 DifferenceOfSquares 5

# difference of squares 100?
⍤⤙≍ 25164150 DifferenceOfSquares 100
