~ "bob.ua" ~ HeyBob

# prolonged silence?
⍤⤙≍ "Fine. Be that way!" HeyBob "    "

# silence?
⍤⤙≍ "Fine. Be that way!" HeyBob ""

# shouting numbers?
⍤⤙≍ "Whoa, chill out!" HeyBob "1 2 3 GO!"

# no letters?
⍤⤙≍ "Whatever." HeyBob "1 2 3"

# question with no letters?
⍤⤙≍ "Sure." HeyBob "4?"

# multiple line question?
⍤⤙≍ "Whatever." HeyBob "Does this cryogenic chamber make me look fat?\nno"

# asking a question?
⍤⤙≍ "Sure." HeyBob "Does this cryogenic chamber make me look fat?"

# statement containing question mark?
⍤⤙≍ "Whatever." HeyBob "Ending with ? means a question."

# shouting with no exclamation mark?
⍤⤙≍ "Whoa, chill out!" HeyBob "I HATE YOU"

# using acronyms in regular speech?
⍤⤙≍ "Whatever." HeyBob "It's OK if you don't want to go to the DMV."

# speaking forcefully?
⍤⤙≍ "Whatever." HeyBob "Let's go make out behind the gym!"

# stating something?
⍤⤙≍ "Whatever." HeyBob "Tom-ay-to, tom-aaaah-to."

# shouting?
⍤⤙≍ "Whoa, chill out!" HeyBob "WATCH OUT!"

# forceful question?
⍤⤙≍ "Calm down, I know what I'm doing!" HeyBob "WHAT THE HELL WERE YOU THINKING?"

# prattling on?
⍤⤙≍ "Sure." HeyBob "Wait! Hang on. Are you going to be OK?"

# asking a numeric question?
⍤⤙≍ "Sure." HeyBob "You are, what, like 15?"

# shouting with special characters?
⍤⤙≍ "Whoa, chill out!" HeyBob "ZOMG THE %^*@#$(*^ ZOMBIES ARE COMING!!11!!1!"
