name: saddle-points

dependencies:
  - array
  - base

library:
  exposed-modules: Matrix
  source-dirs: src
  dependencies:
    - containers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - saddle-points
      - hspec
