name: list-ops

dependencies:
  - base

library:
  exposed-modules: ListOps
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - list-ops
      - hspec
