name: spiral-matrix

dependencies:
  - base

library:
  exposed-modules: Spiral
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - spiral-matrix
      - hspec
