name: transpose
version: 1.1.0.1

dependencies:
  - base

library:
  exposed-modules: Transpose
  source-dirs: src
  dependencies:
  - ilist

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - transpose
      - hspec
