~ "resistor-color-trio.ua" ~ Label

# Orange and orange and black
⍤⤙≍ "33 ohms"       Label {"orange" "orange" "black"}

# Blue and grey and brown
⍤⤙≍ "680 ohms"      Label {"blue" "grey" "brown"}

# Red and black and red
⍤⤙≍ "2 kiloohms"    Label {"red" "black" "red"}

# Green and brown and orange
⍤⤙≍ "51 kiloohms"   Label {"green" "brown" "orange"}

# Yellow and violet and yellow
⍤⤙≍ "470 kiloohms"  Label {"yellow" "violet" "yellow"}

# Blue and violet and blue
⍤⤙≍ "67 megaohms"   Label {"blue" "violet" "blue"}

# Minimum possible value
⍤⤙≍ "0 ohms"        Label {"black" "black" "black"}

# Maximum possible value
⍤⤙≍ "99 gigaohms"   Label {"white" "white" "white"}

# First two colors make an invalid octal number
⍤⤙≍ "8 ohms"        Label {"black" "grey" "black"}

# Ignore extra colors
⍤⤙≍ "650 kiloohms"  Label {"blue" "green" "yellow" "orange"}
