~ "space-age.ua" ~ SpaceAge

# age on Earth
⍤⤙≍ 31.69 SpaceAge "Earth" 1000000000

# age on Mercury
⍤⤙≍ 280.88 SpaceAge "Mercury" 2134835688

# age on Venus
⍤⤙≍ 9.78 SpaceAge "Venus" 189839836

# age on Mars
⍤⤙≍ 35.88 SpaceAge "Mars" 2129871239

# age on Jupiter
⍤⤙≍ 2.41 SpaceAge "Jupiter" 901876382

# age on Saturn
⍤⤙≍ 2.15 SpaceAge "Saturn" 2000000000

# age on Uranus
⍤⤙≍ 0.46 SpaceAge "Uranus" 1210123456

# age on Neptune
⍤⤙≍ 0.35 SpaceAge "Neptune" 1821023456

# invalid planet causes error
⍤⤙≍ "not a planet" ⍣(SpaceAge "Sun" 680804807)
