name: sgf-parsing

dependencies:
  - base
  - containers
  - text

library:
  exposed-modules: Sgf
  source-dirs: src
  dependencies:
    - attoparsec

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - sgf-parsing
      - hspec
